[package]
edition = "2024"
name = "snap_rs"
version = "0.1.0"

build = "build/main.rs"

[workspace]
members = ["registry"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lints.clippy]
all = "deny"
enum_glob_use = "deny"
nursery = "deny"
pedantic = "deny"
perf = "deny"
unwrap_used = "deny"

[dependencies]
# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

crab_nbt = {version = "0.2", features = ["serde"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
toml = "0.8"

flate2 = {version = "1.1", features = ["zlib-rs"]}
nom = "8.0"
smol = "2.0"

bitflags = "2.9"
educe = "0.6"
rand = "0.9"
uuid = "1.16"

snap_registry = {path = "registry"}

bytemuck = "1.22"
rgb = {version = "0.8", features = ["bytemuck"]}
thiserror = "2.0"
vek = {version = "0.17", features = []}

[build-dependencies]
convert_case = "0.8"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"

prettyplease = "0.2"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
