# The default config. All options in here are automatically appended to the main config if missing.

[general]
log_level = "info"

[server]
motd = "A Minecraft Server"

[network]
port = 25565
max_players = 20

[network.advanced]
buffer_size = 1024
buffered_packets = 32

compression_threshold = 256
compression_level = 9 # 0 being no compression(fastest), 9 being the best compression(slowest)